"""init2

Revision ID: 4e2ebfd078f7
Revises: 4bdb82f48fac
Create Date: 2026-01-22 14:01:39.772028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2ebfd078f7'
down_revision: Union[str, None] = '4bdb82f48fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('tokenHash', sa.String(length=64), nullable=False),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revokedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tokenHash')
    )
    op.create_index(op.f('ix_refresh_token_userId'), 'refresh_token', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_userId'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
