"""init

Revision ID: a0dc44c37920
Revises:
Create Date: 2026-01-23 13:41:36.372737

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0dc44c37920"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amal_category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "country",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("photoUrl", sa.String(length=500), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "icon",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "location",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("lat", sa.String(length=255), nullable=False),
        sa.Column("lng", sa.String(length=255), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False
        ),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("isVerified", sa.Boolean(), nullable=False),
        sa.Column("isActive", sa.Boolean(), nullable=False),
        sa.Column("isSuperuser", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("dateOfBirth", sa.Date(), nullable=True),
        sa.Column("gender", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("avatarUrl", sa.String(length=500), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    op.create_table(
        "amal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Time(), nullable=False),
        sa.Column(
            "reccuringRule",
            sa.Enum(
                "ONCE",
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "YEARLY",
                name="reccuring_rule_enum",
            ),
            nullable=False,
        ),
        sa.Column("amalCategoryId", sa.UUID(), nullable=True),
        sa.Column("userId", sa.UUID(), nullable=False),
        sa.Column("iconId", sa.UUID(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["amalCategoryId"], ["amal_category.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["iconId"], ["icon.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email_verification",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=255), nullable=False),
        sa.Column("expiresAt", sa.DateTime(), nullable=False),
        sa.Column("userId", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "role", sa.Enum("ASSISTANT", "USER", name="role_enum"), nullable=False
        ),
        sa.Column("userId", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "password_reset_code",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("expiresAt", sa.DateTime(), nullable=False),
        sa.Column("userId", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("userId", sa.UUID(), nullable=False),
        sa.Column("tokenHash", sa.String(length=64), nullable=False),
        sa.Column("expiresAt", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revokedAt", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tokenHash"),
    )
    op.create_index(
        op.f("ix_refresh_token_userId"), "refresh_token", ["userId"], unique=False
    )
    op.create_table(
        "route",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("views", sa.BIGINT(), nullable=False),
        sa.Column("photoUrl", sa.String(length=500), nullable=False),
        sa.Column(
            "category",
            sa.Enum("HAJJ", "UMRAH", "HISTORY", name="category_enum"),
            nullable=False,
        ),
        sa.Column("countryId", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["countryId"], ["country.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "amal_completion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("amalId", sa.UUID(), nullable=False),
        sa.Column("userId", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("completedAt", sa.DateTime(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["amalId"], ["amal.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["userId"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("amalId", "date", name="uq_amal_completion_amal_date"),
    )
    op.create_table(
        "amal_template",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "reccuringRule",
            sa.Enum(
                "ONCE",
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "YEARLY",
                name="reccuring_rule_enum",
            ),
            nullable=False,
        ),
        sa.Column("routeId", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["routeId"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photoUrl", sa.String(length=500), nullable=False),
        sa.Column("avgScore", sa.Float(), nullable=False),
        sa.Column("scoreCount", sa.BIGINT(), nullable=False),
        sa.Column("avgPrice", sa.Float(), nullable=False),
        sa.Column("routeId", sa.UUID(), nullable=False),
        sa.Column("locationId", sa.UUID(), nullable=True),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["locationId"], ["location.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["routeId"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "restaurant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photoUrl", sa.String(length=500), nullable=False),
        sa.Column("avgScore", sa.Float(), nullable=False),
        sa.Column("scoreCount", sa.BIGINT(), nullable=False),
        sa.Column("isHaram", sa.Boolean(), nullable=False),
        sa.Column(
            "costLevel",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="cost_level_enum"),
            nullable=False,
        ),
        sa.Column("routeId", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["routeId"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "route_image",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("routeId", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updatedAt",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["routeId"], ["route.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("route_image")
    op.drop_table("restaurant")
    op.drop_table("hotel")
    op.drop_table("amal_template")
    op.drop_table("amal_completion")
    op.drop_table("route")
    op.drop_index(op.f("ix_refresh_token_userId"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_table("password_reset_code")
    op.drop_table("message")
    op.drop_table("email_verification")
    op.drop_table("amal")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("location")
    op.drop_table("icon")
    op.drop_table("country")
    op.drop_table("amal_category")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
    # ### end Alembic commands ###
